<?php
	
	/***************************************************************
	 * SECTION 0 - MENU
	 *
	 * Menu configuration.
	 ***************************************************************/
	$GLOBALS['menu'] = array(
		
		// French
		'fr' => array(
			'01' => array(
				'title' => 'à propos',
				'class' => 'menu-green',
				'href' => 'a-propos',
				'addKey' => true,
				'keySep' => '.<br />',
				'accesskey' => true,
				'subitems' => array(
					'01' => array(
						'title' => 'Jean-David Gadina',
						'href' => 'macmade',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array()
					),
					'02' => array(
						'title' => 'Luigi Iannitelli',
						'href' => 'keizo',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array()
					)
				),
			),
			'02' => array(
				'title' => 'clients',
				'class' => 'menu-orange',
				'href' => 'clients',
				'addKey' => true,
				'keySep' => '.<br />',
				'accesskey' => true,
				'subitems' => array(),
			),
			'03' => array(
				'title' => 'portfolio',
				'class' => 'menu-blue',
				'href' => 'portfolio',
				'addKey' => true,
				'keySep' => '.<br />',
				'accesskey' => true,
				'subitems' => array(),
			),
			'04' => array(
				'title' => 'typo3',
				'class' => 'menu-red',
				'href' => 'typo3',
				'addKey' => true,
				'keySep' => '.<br />',
				'accesskey' => true,
				'subitems' => array(
					'01' => array(
						'title' => 'logiciels libres',
						'href' => 'logiciels-libres',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(
							'a' => array(
								'title' => 'sélection',
								'href' => 'selection',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'b' => array(
								'title' => 'brevet logiciel',
								'href' => 'brevet-logiciel',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'c' => array(
								'title' => 'manifeste gnu',
								'href' => 'manifeste-gnu',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'd' => array(
								'title' => 'gnu / gpl',
								'href' => 'gnu-gpl',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'e' => array(
								'title' => 'benchmark',
								'href' => 'benchmark',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'f' => array(
								'title' => 'contribuer',
								'href' => 'contribuer',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'g' => array(
								'title' => 'bill ou linus',
								'href' => 'bill-linus',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
						),
					),
					'02' => array(
						'title' => 'points forts',
						'href' => 'points-forts',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(),
					),
					'03' => array(
						'title' => 'fonctionnalités',
						'href' => 'fonctionnalites',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(),
					),
					'04' => array(
						'title' => 'extensions',
						'href' => 'extensions',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(
							'a' => array(
								'title' => 'roadmap',
								'href' => 'roadmap',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
						),
					),
					'05' => array(
						'title' => 'formations',
						'href' => 'formations',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(),
					),
					'06' => array(
						'title' => 'ressources',
						'href' => 'ressources',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(
							'a' => array(
								'title' => 'localisation',
								'href' => 'l10n',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
						),
					),
					'07' => array(
						'title' => 'videos',
						'href' => 'videos',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(),
					),
					'08' => array(
						'title' => 't3fruni2005',
						'href' => 't3fr-uni-2005',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(
							'a' => array(
								'title' => 'participants',
								'href' => 'participants',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'b' => array(
								'title' => 'ergonomie',
								'href' => 'ergonomie',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'c' => array(
								'title' => 'e-learning',
								'href' => 'e-learning',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'd' => array(
								'title' => 'css',
								'href' => 'css',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'e' => array(
								'title' => 'développement',
								'href' => 'developpement',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'f' => array(
								'title' => 'extensions',
								'href' => 'extensions',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'g' => array(
								'title' => 'tsconfig',
								'href' => 'tsconfig',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'h' => array(
								'title' => 'typoscript',
								'href' => 'typoscript',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'i' => array(
								'title' => 'les photos',
								'href' => 'photos',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
						),
					),
					'09' => array(
						'title' => 't3fruni2006',
						'href' => 't3fr-uni-2006',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(
							'a' => array(
								'title' => 'programme',
								'href' => 'programme',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'b' => array(
								'title' => 'inscription',
								'href' => 'inscription',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'c' => array(
								'title' => 'participants',
								'href' => 'participants',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'd' => array(
								'title' => 't-shirts',
								'href' => 't-shirts',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'e' => array(
								'title' => 'infos pratiques',
								'href' => 'infos-pratiques',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'f' => array(
								'title' => 'repas',
								'href' => 'repas',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'g' => array(
								'title' => 'interview',
								'href' => 'interview',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'h' => array(
								'title' => 'les photos',
								'href' => 'photos',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'i' => array(
								'title' => 'conférences',
								'href' => 'conferences',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
								'subitems' => array(
									array(
										'title' => 'typo3',
										'href' => 'typo3',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'accessibilité',
										'href' => 'accessibilite',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'ergonomie',
										'href' => 'ergonomie',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'etat de vaud',
										'href' => 'etat',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'dam',
										'href' => 'dam',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'e-learning',
										'href' => 'e-learning',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'opensource',
										'href' => 'opensource',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
								),
							),
							'j' => array(
								'title' => 'ateliers',
								'href' => 'ateliers',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
								'subitems' => array(
									array(
										'title' => 'install linux',
										'href' => 'installation-linux',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'install windows',
										'href' => 'installation-windows',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'templavoila',
										'href' => 'templavoila',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'typoscript',
										'href' => 'typoscript',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'developpement',
										'href' => 'developpement',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
									array(
										'title' => 'extensions',
										'href' => 'extensions',
										'addKey' => false,
										'keySep' => '. ',
										'accesskey' => true,
									),
								),
							),
							'k' => array(
								'title' => 'partenaires',
								'href' => 'partenaires',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
							'l' => array(
								'title' => 'presse',
								'href' => 'presse',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
						),
					),
					'10' => array(
						'title' => 't3board07',
						'href' => 't3board07',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
						'subitems' => array(
							'a' => array(
								'title' => 'podcast',
								'href' => 'podcast',
								'addKey' => true,
								'keySep' => '. ',
								'accesskey' => true,
							),
						),
					),
				),
			),
			'05' => array(
				'title' => 'divers',
				'class' => 'menu-pink',
				'href' => 'divers',
				'addKey' => true,
				'keySep' => '.<br />',
				'accesskey' => true,
				'subitems' => array(
					'a' => array(
						'title' => 'news',
						'href' => 'news',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
					),
					'b' => array(
						'title' => '3d',
						'href' => '3d',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
					),
					'c' => array(
						'title' => 'print',
						'href' => 'print',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
					),
					'd' => array(
						'title' => 'wallpapers',
						'href' => 'wallpapers',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
					),
					'e' => array(
						'title' => 'flash',
						'href' => 'flash',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
					),
					'f' => array(
						'title' => 'code',
						'href' => 'code',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
					),
					'g' => array(
						'title' => 'php cgl',
						'href' => 'php-cgl',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
					),
					'h' => array(
						'title' => 'phpoems',
						'href' => 'phpoems',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
					),
					'i' => array(
						'title' => 'widgets',
						'href' => 'widgets',
						'addKey' => true,
						'keySep' => '. ',
						'accesskey' => true,
					),
				),
			),
			'06' => array(
				'title' => 'contact',
				'class' => 'menu-purple',
				'href' => 'contact',
				'addKey' => true,
				'keySep' => '.<br />',
				'accesskey' => true,
				'subitems' => array(),
			),
		),
	);
?>
